### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/Kanban#12]
Que uso para manejar rutas ? **React-route** ?

En mis primeras experiencias con `react-route` siempre explota alguna dependencia :/ suele ser asi?

**Comment by Xabadu** [comment]
React Router si es que no estoy usando ningún framework.

Qué dependencia está fallando?

**Comment by cristofer-dev** [comment]
Con la version `react-router@4.0.0-alpha.4` explotaba en `react-broadcast@0.1.2`
Baje a la version `react-router@3.x` pero me pedia revisar el `return` del `render()`

Quizas deberia trabajaar con la ultima versión ? (use la `react-router@4.0.0-alpha.4` por que es la que usan en el curso que estoy siguiendo)

Esta es la [rama](https://github.com/cristofer-dev/TrainerReact/blob/error-react-router/src/components/App/index.jsx) donde subi lo que tengo.

**Comment by cristofer-dev** [comment]
Instale `react-route-dom` en esta [Rama](https://github.com/cristofer-dev/TrainerReact/blob/add-react-route/src/components/App/index.jsx)

y quedo algo asi:
```
<Switch>
        <Route exact path='/' render={ () => (
          <div>
            <Header/>
            <Main user={this.state.user}/>
          </div>
        )}/>

        <Route path='/pagina2' render={ () => (
          <div>
            Pagina 2
          </div> 
        )}/>
</Switch>
```

Para el `path='/'` renderiza sin problema, pero el `path='pagina2'` no funciona.

Alguna idea ?

![captura de pantalla de 2017-12-29 01-02-52](https://user-images.githubusercontent.com/16719664/34429205-b8628178-ec33-11e7-8653-841c2a5b78ba.png)

**Comment by cristofer-dev** [comment]
En webpack se debe habilitar 

```
devServer: {
  host: '0.0.0.0',
  port: 5000,
  inline: true,
  historyApiFallback: true
}
```


Se agrego la linea `historyApiFallback: true`
