### ISSUE TITLE
setear un className usando el valor de un props

### ISSUE THREAD

**Issue by cristofer-dev** [cristofer-dev/Kanban#2]
Si tengo el Componente

```
<div className={`col-md-3 ${styles.column} `}>      
    {this.props.action}
</div>
```

hay forma de usare el `{this.props.action}` dentro de `${styles.xxxx}`, siendo `xxxx` el valor de `{this.props.action}` para asignar clases **dinamicas** al componente según el valor del `props` que reciba ?

**Comment by Xabadu** [comment]
Si, hay 2 formas de llamar los atributos o propiedades de un objeto: Una es `dot notation` que es la clásica que vemos siempre (`objeto.key`) y esa es la más usada cuando sabes el nombre de la key y no cambiará. Para atributos o propiedades dinámicos se usa otra notación que es con brackets: `objeto[key]`, y en ese key puedes pasarle una variable y la interpretará.

**Comment by cristofer-dev** [comment]
`${styles[this.props.action]}`

Thanks!
