### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by fforres** [cristofer-dev/Kanban#6]
- Crear un "archivo lock", Como `yarn.lock` o `package-lock.json` para poder dejara las dependencias super definidas. 
> Por ejemplo, en el `package.json` esta definido que `babel-preset-react` use la version `^6.24.1` ese `^` quiere decir que cuando tires `npm install`, va a ir.a buscar cualquier version sobre la 6.24.1 que este disponible. Quizás no pasa nada, o quizás la versión 6.25.4 rompe todo... nunca se sabe :p 
> La idea del `yarn.lock` o `package-lock.json` es que define dependencias exactas, para que tengas builds "predecibles" cuando buildeas en local, o en un servidor, o en un entorno de CI/CD.

- Crear un archivo .gitignore donde agregies cosas que no quieres que se suban
> `node_modules`, `build` son buenos ejemplos (quizás tb la carpeta .git o una carpeta .logs que se cree automaticamente? hay algunos ejemplos cool acá https://github.com/github/gitignore )

- Configurar un [Linter](http://eslint.org/) en la app
> Apañan a que cuando otro wn quiera meter código, no tome sus propias deciciones de estilo (a mi me gustan los `;` y agregar `,` al final de los objetos) te ahorras discusiones y peleas por tonteras :p 
> Esto puedes hacerlo instalando eslint `yarn add eslint --dev` o `npm install eslint --dev` y luego corriendo esa instalación local de eslint `./node_modules/.bin/eslint --init`, acá hay más info https://eslint.org/docs/user-guide/getting-started#local-installation-and-usage. 

Con el tema del linter, quizás quieres instalar un linter en tu IDE para que te muestre esos cambios mientras escribes, acá hay caleeeta de integraciones https://eslint.org/docs/user-guide/integrations

---------

Extra ultra cool, pero después que instales el linter, puedes usar [Travis](https://travis-ci.com/) para que corra **en cada PR**, la validación del linter, y que no te deje mergear la rama si el linter tiene algún error.
> (Después esas validaciones las puedes expandir pa que corra tests, que valide si hay servidores arriba, o que tire a produccíon al tiro si pasa algo y 1000 cosas más 😛 )

**Comment by cristofer-dev** [comment]
- *lock*
> `yarn.lock` cuando uso *yarn*
> `package-lock.json` cuando uso *npm*

- *gitignore*
> Ignorados y se envio un nuevo PR
> Se puede ignorar la `.git`

- *Lint*
> Tengo ESLin en local... no inluyo el rc , lo agrego al repo ?

**Comment by fforres** [comment]
Con lo de ESLint, es bueno tener una versión local, (Los IDEs siempre buscan primero antes de buscar la instalación global :p) y asi cuando alguien se baje tu app, va a ver lo mismo que tu :)
